Handle datastore id mismatch
Handle the corner case where a returned datastore id
may not match the id in the current terraform state.
This should never happen because id's are immutable.

If it does ever occur we will not overwrite any state
and will instead raise this error:

```
Error: error reading datastore

  with hpegl_pc_datastore.test,
  on terraform_plugin_test.tf line 21, in resource "hpegl_pc_datastore" "test":
  21:   resource "hpegl_pc_datastore" "test" {

'id' mismatch: 698de955-87b5-5fe6-b683-78c3948beede !=
698de955-87b5-5fe6-b683-78c3948beede
```