Handle hypervisor cluster id mismatch
Handle the corner case where a returned id may not match the id in the
current terraform state.  This should never happen because id's are
immutable.

If it does ever occur we will not overwrite any state
and will instead raise this error:

```
Error: error reading hypervisor cluster 298a299e-78f5-5acb-86ce-4e9fdc290ab7

  with hpegl_pc_hypervisor_cluster.test,
  on terraform_plugin_test.tf line 21, in resource "hpegl_pc_hypervisor_cluster" "test":
  21:   resource "hpegl_pc_hypervisor_cluster" "test" {

'id' mismatch: 298a299e-78f5-5acb-86ce-4e9fdc290ab7 !=
298a299e-78f5-5acb-86ce-4e9fdc290ab7
```